name: Manual Notebook Execution
on:
  workflow_dispatch:

jobs:
  ScheduledBuild:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_scheduled.yml@v2
   secrets:
      CASJOBS_USERID: ${{ secrets.CASJOBS_USERID }}
      CASJOBS_PW: ${{ secrets.CASJOBS_PW }}
      
